# Generated by Django 5.2.2 on 2025-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsletter_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
